[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font Propo"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Control"

[window]
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"
